apiVersion: apps/v1
kind: Deployment
metadata:
  name: autocert-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autocert
  template:
    metadata:
      labels:
        app: autocert
    spec:
      containers:
      - name: auto-cert
        image: localhost:5000/auto-cert:latest
        ports:
        - containerPort: 7000
        volumeMounts:
        - name: ansible-vault-volume
          mountPath: /mnt/
      volumes:
      - name: ansible-vault-volume
        hostPath:
          path: /home/pitemp/ansible-vault/
          type: Directory