apiVersion: apps/v1
kind: Deployment
metadata:
  name: autocert-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autocert
  template:
    metadata:
      labels:
        app: autocert
    spec:
      containers:
      - name: autocert
        image: localhost:5000/autocert:latest
        ports:
        - containerPort: 7000
        volumeMounts:
        - name: ansible-vault-volume
          mountPath: /mnt/
        - name: config-volume
          mountPath: /root/config/configcerts.ini
          subPath: config.ini
          readOnly: true
        env:
        - name: ANSIBLE_VAULT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: secrets
            key: ANSIBLE_VAULT_PASSWORD
      volumes:
      - name: ansible-vault-volume
        persistentVolumeClaim:
          claimName: host-pvc
      - name: config-volume
        secret:
          secretName: secrets