apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  config.ini: {{ .Files.Get "config/configcerts.ini" | b64enc | quote}}
  ANSIBLE_VAULT_PASSWORD: {{ .Files.Get "config/password.txt" | b64enc | quote }}