- name: Deploy and execute ros2 shim on k3s agent nodes
  hosts: k3s_agents
  become: yes  # Use sudo to become root
  vars_files:
    - /mnt/ansible-vault/token_shim.yaml
    - /mnt/ansible-vault/token_key_ctrl.yaml
  tasks:
    - name: Copy token to target node
      copy:
        content: "{{ token }}"
        dest: "{{ lookup('env', 'CUSTOM_HOME') }}/ros2-node-shim/ca/token_shim.txt"
        mode: '0644'
    
    - name: Copy token key to target node
      copy:
        content: "{{ token_key }}"
        dest: "{{ lookup('env', 'CUSTOM_HOME') }}/ros2-node-shim/ca/token_key_ctrl.txt"
        mode: '0644'